name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/graphable
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Install uv
        uses: astral-sh/setup-uv@f98609f8591bc595679f07a4485163913017f169 # v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491f01dee05 # v5
        with:
          python-version-file: ".python-version"

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@67339c7aa57059a7446044a755523c97a3a39162 # v1.12.4
